### ISSUE TITLE
About the CMakeLists.txt

### ISSUE THREAD

**Issue by toyoxx** [unr-arl/cortex_ros_bridge#1]
I'm building cortex_ros_bridge package in ROS Jade, and I run into two problems.

1. In the service cortexSetOrigin.srv, there was a heading with comments. Apparently on this version of ROS comments in the service definition are not allowed, because the message generator was complaining. Removing the comment solved the issue. 

2. In the CMakeLists.txt there are two targets which I think might not be related with the project. 

```
add_executable(temp_controller src/temp_controller.cpp)
target_link_libraries(temp_controller ${catkin_LIBRARIES})

add_executable(pid_controller src/pid_controller.cpp)
target_link_libraries(pid_controller ${catkin_LIBRARIES})
```

If they are, you should upload them to the repo. I commented them and the compilation seemed to go well.

Additionally, it would be great if you included where to put the cortex_linux_sdk files into the README (.cpp in the src folder, .h in the include folder?), I had to do a bit of guessing.

Thank you very much!

**Comment by tsorey** [comment]
Thanks a bunch! I apologize for the oversight, those things should be/have been removed from the repo. I will also update the README to include locations for the cortex files. Thanks for bringing this to my attention!

**Comment by happygaoxiao** [comment]
@toyoxx @tsorey  Hello everyone, have you ever met the problem that data is jammed? I use less than three markers for motion capture. Everything works fine. But if more than four markers, the real-time update data is not as the frequency of 250Hz. The interval of time stamp is 6ms, 8ms, or even 40ms. I don't know what happened. Could you please help me?
