### ISSUE TITLE
Error: Unable to initialize ethernet communication

### ISSUE THREAD

**Issue by happygaoxiao** [unr-arl/cortex_ros_bridge#2]
Thanks for your driver. I have met a problem as:
` Error: Unable to initialize ethernet communication`

The ubuntu computer and the windows computer with Cortex are in a local area network 10.1.1.xxx. The Ports are set as your README file. I have checked the code in [cortex_bridge](https://github.com/unr-arl/cortex_ros_bridge/blob/7be93097db2c267f329ce26516cf5f3ccfb81637/src/cortex_bridge.cpp#L94). The IPs of two computer are correct with my manual assignment.

Could you give me some help? I am using the same environment with Ubuntu 14.04, ROS Indigo, and Cortex 5.5.

**Comment by happygaoxiao** [comment]
In additation, the return value of the function `gethostbyaddr` in `cortex_socket.cpp` is `NULL`.


    haddr = gethostbyaddr((char *) &addr, 4, AF_INET);
    if (haddr != NULL) {
      Address->s_addr = addr;
      return 0;
    }

**Comment by happygaoxiao** [comment]
Thanks for all your works! It works. Thanks so much.

**Comment by rossj13** [comment]
What was the solution for this?

**Comment by happygaoxiao** [comment]
@rossj13  Are you sure you have set the IP address and port correctly?  Besides, a rigid frame body should be set at Cortex.
